### ISSUE TITLE
what is $rowId

### ISSUE THREAD

**Issue by ilbeygi** [mateusjatenee/LaravelShoppingcart#7]
hi mateusjatenee
i have a problem.
i dont understand about $rowId and dont know that how to can i use from $rowId ??? 🎱 

please help me :((

tank you ...

**Comment by projct1** [comment]
+

**Comment by mateusjatenee** [comment]
Hi guys,  

Sorry for the late answer. I had surgery and was unable to use the computer.  

The row id is simply an identifier for each row. [Take a look at this](https://github.com/mateusjatenee/LaravelShoppingcart/blob/master/src/CartItem.php#L392).

**Comment by projct1** [comment]
Ok, thanks :)
